---
- name: Deploy Nginx Pod
  hosts: all
  gather_facts: no
  tasks:
    - name: Deploy Nginx
      community.kubernetes.k8s:
        kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            labels:
              app: nginx
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                  - containerPort: 80
